### ISSUE TITLE
fabric-admin-sdk draft proposal

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/fabric-admin-sdk#1]
# Project Name 
fabric-admin-sdk

## motivation
As gateway sdk will drop off admin capacity, we plan to recover admin capacity related things with this project proposal.

## identified features
- chain code lifecycle
- system chain code(as list all chain code)
- channel operators
1. new channel
1. channel update(new org join into specific channel)
1. peer join channel
1. peer exit channel
1. list channel 
1. inspect channel config
- gate policy?(common/policydsl/policyparser.go, tool for operator)
- peer discovery(optional, as ping test among peer networks when gateway disabled or fabric version below 2.5)
- base on peer discovery result, generate connection profile for sdk if possible?(optional)

**Comment by davidkhala** [comment]
quoted from @jt-nti
> Some useful for an admin sdk. Newly published fabric-protos
> go: github.com/hyperledger/fabric-protos-go-apiv2
> nodejs: www.npmjs.com/package/@hyperledger/fabric-protos
> java: to be released to maven

**Comment by SamYuan1990** [comment]
pre discussed with @jkneubuh ,
to further considering with decouple peer cli and peer server works in fabric, for golang code implementation, we'd better considering existing fabric code and structure if there possible. 
question to @jt-nti or @davidkhala , are we able to have original repo as reference? I suppose original code repo will better than npm release page.

**Comment by SamYuan1990** [comment]
> https://github.com/hyperledger/fabric-protos/packages/1412970

don‘t worry i founf it as https://github.com/hyperledger/fabric-protos

**Comment by SamYuan1990** [comment]
hi guys, if there no further comments for this issue, I plan to update into documentations and close this issue with a pr.
