### ISSUE TITLE
repo infrastructure

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/fabric-admin-sdk#5]
- [x] #6
- [x] #7
- [x] #11
- [x] #12
- [ ] github action for go release
- [ ] github action for java ci/cd
- [ ] github action for java e2e testing base on test-network
- [ ] github action for java release
- [ ] github action for nodejs(or typescript) ci/cd
- [ ] github action for nodejs(or typescript) e2e testing base on test-network
- [ ] github action for nodejs(or typescript) release

**Comment by davidkhala** [comment]
which test-network bootstrap tool we plan to use first?

**Comment by SamYuan1990** [comment]
test-network from fabric sample?

**Comment by SamYuan1990** [comment]
ideally, for e2e
- we are going to use test-network to start a fabric network without channel
- use script to create channel and deploy chaincode
- invoke test-network to start an invoke and query

**Comment by davidkhala** [comment]
> test-network from fabric sample?

- I would like to vote + 1 for minifab for test-network. 
- create channel and deploy chaincode are the functions to be tested here. So I think they are part of integration test, and I am thinking of a graceful `afterTest` cleanup, including unjoin channel, remove the installed chaincode (if possbile).
- Can we use fabric-gateway as method to invoke/query test-network?

**Comment by SamYuan1990** [comment]
> > test-network from fabric sample?
> 
> * I would like to vote + 1 for minifab for test-network.
> * create channel and deploy chaincode are the functions to be tested here. So I think they are part of integration test, and I am thinking of a graceful `afterTest` cleanup, including unjoin channel, remove the installed chaincode (if possbile).
> * Can we use fabric-gateway as method to invoke/query test-network?

in my point of view, if we are going to provide a strander SDK, 1st CI should better following up official user guide.
for minifab or other fabric network build up tools as for sample fabric-operator, in this case as they are not official user guide(fabric official document for now) they are the same priority as test-network-k8s.

yes, e2e equals integration test, but not `afterTest` clean up, as I thought we don't have remove chaincode feature in fabric? or event remove channel from orderer.

for fabric gateway, it's a good questions.
ideally, we'd better have the same data model with fabric source code or gateway. at point of test chaincode ready with invoke or query, gateway sdk is same with shell script.
However, if we further thought we basing on this admin-sdk to help implementation for decouple peer server with peer cli command. which means we are going to have a cli basing on this sdk repo in the future. then the invoke is better to be tested with shell script but not by gateway sdk.(to follow same user experience with official document.)

**Comment by davidkhala** [comment]
I found a hacky way to remove the installed chaincode. To `rm` the related chaincode files in `peer` and then restart the peer to let it detect the change.

**Comment by SamYuan1990** [comment]
> I found a hacky way to remove the installed chaincode. To `rm` the related chaincode files in `peer` and then restart the peer to let it detect the change.

but the chaincode information recording still at channel right?
